### ISSUE TITLE
Frequently running into "ResourceExhaustedError"

### ISSUE THREAD

**Issue by raj-sivakumar** [Large-Scale-Tensor-Decomposition/tensorD#16]
When trying to do a tucker decomposition over a batch of 4-D tensors I'm frequently running into memory issues. This persists even when trying to decompose a single tensor. I am working with 2 Titan GPUs and am somehow using up the view RAM completely. Is there a solution you might offer in this situation?

**Comment by AgentDS** [comment]
I used to have similar issue (on CPU) and I fixed it on my local branch. Now I have merged it into the master branch. Maybe you can try the new version
