### ISSUE TITLE
HOOI tucker decomposition does not work more than once

### ISSUE THREAD

**Issue by neen113** [Large-Scale-Tensor-Decomposition/tensorD#19]
I am trying to run hooi tucker decomposition on an image multiple times, however, it only works the first time I call the hooi train function. You can replicate the problem with the following code:

`for i in range(2):
        data_provider = Provider()
        X = np.arange(60).reshape(3, 4, 5)
        data_provider.full_tensor = lambda: X
        hooi_env = Environment(data_provider, summary_path='/tmp/tensord')
        hooi = HOOI(hooi_env)
        args = hooi.HOOI_Args(ranks=[2, 2, 2], validation_internal=5)
        hooi.build_model(args)
        hooi.train(100)
        print(hooi.full - X)`

**Comment by AgentDS** [comment]
maybe you can try this:
`    for i in range(2):
        g1 = tf.Graph()
        data_provider = Provider()
        X = np.arange(60).reshape(3, 4, 5)
        data_provider.full_tensor = lambda: X
        hooi_env = Environment(data_provider, summary_path='/tmp/tensord')
        hooi = HOOI(hooi_env)
        args = hooi.HOOI_Args(ranks=[2, 2, 2], validation_internal=5)
        with g1.as_default() as g:
            hooi.build_model(args)
            hooi.train(100)
        print(np.sum(hooi.full - X))
        tf.reset_default_graph()`

**Comment by AgentDS** [comment]
You can use tf.Graph() to separate two decompositions:
```
    for i in range(2):
        g1 = tf.Graph()
        data_provider = Provider()
        X = np.arange(60).reshape(3, 4, 5)
        data_provider.full_tensor = lambda: X
        hooi_env = Environment(data_provider, summary_path='/tmp/tensord')
        hooi = HOOI(hooi_env)
        args = hooi.HOOI_Args(ranks=[2, 2, 2], validation_internal=5)
        with g1.as_default() as g:
            hooi.build_model(args)
            hooi.train(100)
        print(np.sum(hooi.full - X))
        tf.reset_default_graph()
```
