### ISSUE TITLE
The example doesn't work.

### ISSUE THREAD

**Issue by oratosa** [Large-Scale-Tensor-Decomposition/tensorD#24]
I tried the example on the README but it didn't work well as follows.
Could you check the program?

![image](https://user-images.githubusercontent.com/49934427/79728286-a5b11d80-8328-11ea-964b-4f3aa4f27255.png)

**Comment by AgentDS** [comment]
Could you please check the TensorFlow version?

**Comment by AgentDS** [comment]
When we developed this project, TensorFlow is 1.2.1.
I guess maybe you could reinstall the old version of TensorFlow since TensorFlow has been updated so fast.
